name: CI

on:
  push:
    branches: [ main ]

jobs:
  ci:
    name: PHP ${{ matrix.php }}${{ matrix.multisite && ' multisite' || '' }}${{ matrix.wordpress != '' && format( ' (WP {0}) ', matrix.wordpress ) || '' }} on ubuntu-latest
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
        fail-fast: true
        matrix:
            php: ['8.2', '7.4']
            multisite: [false]
            wordpress: ['6.3', '5.9']
    env:
        WP_ENV_PHP_VERSION: ${{ matrix.php }}
        WP_ENV_CORE: ${{ matrix.wordpress == '' && 'WordPress/WordPress' || format( 'https://wordpress.org/wordpress-{0}.zip', matrix.wordpress ) }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js and install dependencies
        uses: ./.github/setup-node

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
            php-version: '${{ matrix.php }}'
            ini-file: development
            coverage: none

      - name: Override PHP version in composer.json
        run: composer config platform.php ${{ matrix.php }}

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: "lowest"
          custom-cache-suffix: $(/bin/date -u --date='last Mon' "+%F")

      - name: Start Docker environment
        run: npm run wp-env start

      - name: Log running Docker containers
        run: docker ps -a

      - name: Running single site unit tests
        run: |
            npm run test:unit:php

      - name: Running single site e2e tests
        run: |
            npx playwright install chromium
            npm run test:e2e
